[phases.build]
cmds = ["composer install --no-dev", "npm ci", "npm run build"]

[phases.deploy]
cmds = ["php artisan migrate:fresh --seed --force", "php artisan optimize:clear"]

[start]
cmd = "php-fpm -D && nginx -g 'daemon off;' -c /app/nginx.conf"