[phases.build]
cmds = ["composer install --no-dev", "npm ci", "npm run build", "php artisan optimize:clear"]

[phases.deploy]
cmds = ["php artisan migrate:fresh --seed --force"]

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"